#!/bin/sh

function help () {
    echo "";
    echo "Simon's git helper version 0.2";
    echo "";
    echo "    sgh commit \"message\"    - commits changes from branch to master";
    echo "    sgh pull                  - pulls master and merges with branch (only works if no changes are to commit)";
    echo "    sgh help                  - shows this help message";
    echo "";
    echo "Special thanks to Timo König for the idea";
    echo "";
}

function check () {
    if [ $1 != 0 ]
    then
        echo ""
        echo "sgh(): An error occurred"
        echo "sgh(): exiting"
        echo ""
        exit 1;
    fi
}

MASTER_NAME="master"
BRANCH_NAME="development"
    
if [ $1 ]
then
    # do stuff
    case "$1" in
        commit)
            if [ "$2" ]
            then
                echo "sgh(): Starting Commit"
                echo ""
                echo "sgh(): Creating branch -> $BRANCH_NAME"
                git checkout -b $BRANCH_NAME
                if [ $? != 0 ]
                then
                    echo "sgh(): Switching to branch -> $BRANCH_NAME"
                    git checkout $BRANCH_NAME
                fi
                echo ""
                echo "sgh(): Adding files"
                git add -A .
		check $?
		
                echo ""
                echo "sgh(): Committing changes"
                git commit -m "$2"
		check $?
		
                echo ""
                echo "sgh(): Checkout to $MASTER_NAME branch"
                git checkout $MASTER_NAME
                
                echo ""
                echo "sgh(): pull current master"
                git pull
                check $?
                
                echo ""
                echo "sgh(): Checkout to $BRANCH_NAME branch"
                git checkout $BRANCH_NAME
                
                echo ""
                echo "sgh(): doing rebase 'n' shit"
                git rebase $MASTER_NAME
                check $?
                
                echo ""
                echo "sgh(): Checkout to $MASTER_NAME branch"
                git checkout $MASTER_NAME
                
                echo ""
                echo "sgh(): Merging $MASTER_NAME with $BRANCH_NAME"
                git merge $BRANCH_NAME
                check $?
                
                echo ""
                echo "sgh(): Push to Master"
                git push
                check $?
                
                echo ""
                echo "sgh(): Switching back to $BRANCH_NAME branch"
                git checkout $BRANCH_NAME
                
                echo ""
                echo "sgh(): Ending Commit"
            else
                echo "sgh(): please enter a commit message"
            fi
        ;;
        pull)
            echo "sgh(): Starting Pull"
            echo ""
            echo "sgh(): checkout to $MASTER_NAME"
            git checkout $MASTER_NAME
            
            echo ""
            echo "sgh(): pull current master"
            git pull
            check $?
            
            echo ""
            echo "sgh(): Creating branch if not exists -> $BRANCH_NAME"
            git branch $BRANCH_NAME
            
            echo ""
            echo "sgh(): doing rebase 'n' shit"
            git rebase $BRANCH_NAME
            check $?
            
            echo ""
            echo "sgh(): Checkout to $BRANCH_NAME branch"
            git checkout $BRANCH_NAME
            
            echo ""
            echo "sgh(): Merging $BRANCH_NAME with $MASTER_NAME"
            git merge $MASTER_NAME
            check $?
            
            echo ""
            echo "sgh(): Ending Pull"            
        ;;
        *)
            help
        ;;
    esac
else
    help;
fi
